name: xeus-wren
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  # Host dependencies
  - xeus
  - nlohmann_json
  - cppzmq
  - xtl
  - wren
  # Test dependencies
  - pytest
  - jupyter_kernel_test
  - nbval
  - pytest-rerunfailures
  - doctest

