name: xeus-wren
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  - cxx-compiler
  # Host dependencies
  - xeus>=5.0,<=6
  - xeus-zmq
  - nlohmann_json
  - cppzmq
  - wren
  # Test dependencies
  - pytest
  - jupyter_kernel_test
  - nbval
  - pytest-rerunfailures

