name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  generic:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, win-latest]

    steps:
      - uses: actions/checkout@v2
 
      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
      - name: cmake configure
        shell: bash -l {0}
        run: |
          mkdir -p bld
          cd bld
          cmake .. \
           -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 

      - name: build
        shell: bash -l {0}
        run: |
          cd bld
          cmake --build . --target install --config Release

      - name: install
        shell: bash -l {0}
        run: |
          cd bld
          make install

